### ISSUE TITLE
integration in SF launchpad

### ISSUE THREAD

**Issue by hima4all** [SAP-archive/cloud-sf-extension-cap-sample#2]
hello,
you didn't mention how to include the tiles created in SF launchpad with the same look and feel

thanks
ibrahim

**Comment by piejanssens** [comment]
They don't mention it, because there is no solution for that... 

- With BTP Neo it was possible via the SF site template on the Portal service (super expensive if it's only used as an integration component to embed your extension in). 
- With BTP Cloud Foundry, there is no such option in the CF Portal service and there is also no option to integrate extensions directly in SF. 

There is also nothing on the roadmap unfortunately. 
@indusankar89 Please check internally and let us know.

**Comment by indusankar89** [comment]
Not in immediate scope of SF extensibility. Will update the repository once this comes.
